image: Visual Studio 2017
environment:
  PROJECT_FILE: ./ThirtySecondsOfCSharp/ThirtySecondsOfCSharp.csproj
  TEST_PROJECT_FILE: ./ThirtySecondsOfCSharp.Tests/ThirtySecondsOfCSharp.Tests.csproj
  CODECOV_REPO_TOKEN:
    secure: 3SCQxT7ggbFXZdIaeBX/GNRWzIMQhAzLMJ8dh7ZJwnY6Z7UMnH/fOKUaq/7BLtQD
build_script:
  - cmd: dotnet build %PROJECT_FILE%
  - cmd: dotnet build %TEST_PROJECT_FILE%
test_script:
  - cmd: dotnet test %TEST_PROJECT_FILE%
  - bash coverage.sh
  - bash codecov.sh